# DCO check: every commit in a pull request must carry a "Signed-off-by:" line, which says the author has the
# right to contribute it under the project's licence (the Developer Certificate of Origin). Add it with
# `git commit -s`. See CONTRIBUTING.md, "Sign your commits".
name: DCO

on:
  pull_request:

permissions: {}

jobs:
  sign-off:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read # read the pull request's commits
    steps:
      - name: Check every commit is signed off
        uses: KineticCafe/actions-dco@5f160e3ee086af8fc0fb567b8add0937d074123e # v3.2.0
